# Generated by Django 5.1.7 on 2025-03-18 19:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=10)),
                ('startDate', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('endDate', models.DateField(default=django.utils.timezone.now)),
                ('token', models.CharField(max_length=30)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnqueteResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('responseDatetime', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('validationDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('enqueteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquetes.enquete')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('responseType', models.CharField(max_length=100)),
                ('enqueteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquetes.enquete')),
            ],
        ),
    ]
