# Generated by Django 5.1.7 on 2025-03-20 16:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Enquetes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquete',
            name='statut',
        ),
        migrations.AddField(
            model_name='enquete',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('archive', 'Archivé')], default='actif', max_length=10),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquete',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='enqueteresponse',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('complete', 'Completé'), ('annule', 'Annuler')], default='en_attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='enqueteresponse',
            name='validationDatetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='responseType',
            field=models.CharField(choices=[('text', 'Texte'), ('choix_multiple', 'Choix multiple'), ('boolean', 'OUI/NON')], default='text', max_length=100),
        ),
    ]
