# Generated by Django 5.1.7 on 2025-03-22 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Enquetes', '0002_remove_enquete_statut_enquete_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=255)),
                ('note', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquetes.question')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responseComment', models.TextField(blank=True)),
                ('enqueteResponsesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquetes.enqueteresponse')),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Enquetes.question')),
                ('responseSelectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Responses.responseselection')),
            ],
        ),
    ]
